### ISSUE TITLE
Missing annotated data 

### ISSUE THREAD

**Issue by Nana2929** [zhouhanxie/PRAG#3] opened 2023-12-18 13:44 UTC
Thank you for the great work! 
Apologies for disturbing you these days with 2 issues.
I'd like to ask for your help in providing the 3 missing annotated csv files: `./annotated_data/{dataset}_annotated.csv`  required in `train_generator.py`. 
Furthermore, the dataset download link provided in your readme does not work for me..., this works: https://lifehkbueduhk-my.sharepoint.com/personal/16484134_life_hkbu_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F16484134%5Flife%5Fhkbu%5Fedu%5Fhk%2FDocuments%2FCIKM20%2DNETE%2DDatasets&ga=1
 
Wishing you all the best.

**Comment by zhouhanxie** [comment] 2023-12-18 18:30
Np!

Re. 1 - this is the file mentioned in section 5.3 "This results in a high-quality dataset where each input text is paired with a set of keywords, with a ground-truth answer that contains at least one of the keywords.", basically a way to train UnifiedQA model to contain the keywords we want. 

Back then instruction-following LMs wasn't a thing, so I think you'd be able to achieve good performance by using <Flan T5, Openai Models, Alpaca, ...> and instruct them to include the keyword produced by the estimator when producing the output (since PRAG is a general RAG framework, and we experimented with PRAG-Optimus and PRAG-SUM as well as PRAG-UnifedQA, and the generator seems to always benefit from RAG, I think e.g. PRAG-Alpaca will work too).

Otherwise, the way to go is use [constrained decoding](https://huggingface.co/blog/constrained-beam-search) on [UnifiedQA](https://huggingface.co/allenai/unifiedqa-t5-large) (I used exactly the HuggingFace implementation) to generate some outputs as the first pass, and fix any grammar/inconsistency in the output (can probably just use e.g. GPT-3.5-Turbo now) for further fine-tuning. The input format for UnifedQA training is "keywords,Question(see the questions in guided_generator.py),<evidence>(retriever retrieved reviews, one perline)", output is "the corrected constrained decoding result". (Long shot, but in case if you need exactly PRAG-UnifedQA).


Re. 2

Yeah, I think the dataset itself migrated? As long as you are using the one from [NLG4RS](https://github.com/lileipisces/NLG4RS?tab=readme-ov-file), that'd be the one needed here.

LMN whether this helps/if there are any info needed...

**Comment by Nana2929** [comment] 2023-12-19 00:34
Thank you for the quick reply and detailed clarification! 
I did realize that they are the files you mention in section 5.3. I was just wondering whether you could be so kind to release these files somewhere on the web for us to download (as they are gitignored now, this repo does not contain them), so that the format is self-explanatory and it is easier for us to reproduce the results under a scenario that is closer to your paper experiments. 
Looking forward to your reply.

**Comment by zhouhanxie** [comment] 2023-12-19 03:16
Ah, I see... Unfortunately the exact files are not around anymore - see [issue 1](https://github.com/zhouhanxie/PRAG/issues/1)...

To reproduce though, the file should contains these 4 fields (use [here](https://github.com/zhouhanxie/PRAG/blob/main/guided_generator/train_generator.py#L44)):
- prompt: `"what was great ?"` or `"what was not good ?"`
- topic: keywords generated by the embedding estimator 
- evidence: reviews retrieved by the retriever
- corrected_summary: corrected constrained decoding output (see below).


To get this data, first sample 100 datapoints from dev set of each dataset, Run retriever to get their associated retrieved reviews (you can reuse code blocks from prag_generation folder, I hyperlinked the relevant parts below) and the predicted rating, also, run embedding estimator to get the estimated topic keywords.

Now to get these fields:

- prompt
   - use the [adjustment term](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py#L95) from the retriever, if the retriever-predicted rating is higher than average (adj term is greater than 0), ask `"what was great ?"`, else `"what was not good ?"`.
 - evidence
   - retrived reviews, joined one per line like [this](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py#L117) (the several lines above are also relevant, basically concat the retrieved reviews together)
  - topic
    -  generated keywords from the embedding estimator, cleaned same way as [here](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py#L115), note that there is a [line that enforces topics are from evidence](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py#L120)
 - corrected_summary
   - run UnifedQA by inputting [prompts assembled like this](https://github.com/zhouhanxie/PRAG/blob/main/guided_generator/train_generator.py#L11). However, remove [the line for adding keywords](https://github.com/zhouhanxie/PRAG/blob/main/guided_generator/train_generator.py#L22) when constructing prompt as UnifiedQA won't follow these keywords. Instead, use [_Disjuntive Constraint_](https://huggingface.co/blog/constrained-beam-search) implemented by HF when generating answer from UnifedQA to force at least 1 keyword to appear in the output. This affects quality of generated outout (grammar/fluency etc. due to foced decoding) - so rephrase these outputs so they are free of these errors (manual effort). This is the "corrected_summary" mentioned above.

Now you can dump these into a pandas dataframe and use them to fine-tune UnifedQA.  These are a fairly long shot way to get UnifiedQA to do somewhat do abit  instruction-following so I mentioned alternatives first, but I think you should be able to reproduce what we did by using this procedure. (Basically the data processing would be the same as [generate_review.py](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py#L120))

Hope this helps! LMN if you run into any issues...

**Comment by Nana2929** [comment] 2023-12-19 04:01
Thank you for the explanation! Got it. 
I agree that a properly instruction-tuned LLM may be able to do the desired keyword-constrained text generation with less effort. I will see if I can use LLMs to achieve similar performance.

**Comment by zhouhanxie** [comment] 2023-12-19 04:24
Sg! closing this for now, but feel free to ping again if you have any further question.

**Closed as completed by zhouhanxie** 2023-12-19 04:24 UTC

**Comment by MohammadAmanlou** [comment] 2024-11-30 16:12
Hi,

I am re-opening this issue as I am facing a problem when using the PRAG pipeline on the TripAdvisor dataset. According to the paper [here](https://arxiv.org/pdf/2209.12613), I followed all the preprocessing steps to download and prepare the TripAdvisor data. I then trained both the embedding_interpreter and the personalized_retriever as mentioned in the issue comment [here](https://github.com/zhouhanxie/PRAG/issues/3#issuecomment-1862041136).

Everything works as expected until the step where the topics are generated. The problem is that none of the topics generated from the model are actually found in the evidence. I followed all the steps, including training and data processing, but the generated topics don’t seem to overlap with the evidence in any way.

Could you please help me identify what might be causing this issue? I would greatly appreciate any suggestions or insights.

Thanks!

**Comment by zhouhanxie** [comment] 2024-11-30 17:10
Hi Mohammad -- thanks for your interest in PRAG! A couple of things that might be helpful:

- When the generator (sometimes) cannot identify "salient" keywords in evidence, an empty string will be given to the final generator as topic words (see [these lines](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py#L116)). The framework should still produce grounded reviews based on retrieved evidence and the prompt alone. 
- If you see the keyword generator "de-generating," i.e., generating "the the the the the" or other nonsense sequences, it means the model did not converge and better hyper-parameters are needed.
- Another "hack" you can try is directly filter out high tf-idf keywords in the evidence and use them as the topics (instead of generating them from a model). Since in the couple variants of PRAG we tried (PRAG-Optimus, etc) we observe uniform factuality improvement, my guess is this hack should work alright.

Feel free to ping if there are further issues!

**Comment by MohammadAmanlou** [comment] 2024-12-09 11:25
Thank you so much for your detailed response and helpful suggestions! I was able to resolve the issue by implementing the TF-IDF-based hack you mentioned. The generated topics now align well with the evidence, and the pipeline is producing meaningful results. I really appreciate your support.

I have another question related to fine-tuning the model. Due to hardware limitations (I currently have access to GPUs with less than 24GB of memory), I am unable to fine-tune the UnifiedQA-3b model. Would it be feasible to use the UnifiedQA-base model instead for this purpose? Alternatively, do you have any recommendations for addressing this limitation?

Looking forward to your insights.

Thanks again for all your help!
Mohammad

**Comment by MohammadAmanlou** [comment] 2024-12-14 14:15
Hi ,

I’m still waiting for a response regarding my earlier question about fine-tuning the UnifiedQA model with limited GPU memory. Specifically, I asked if it would be feasible to use UnifiedQA-base instead of the UnifiedQA-3b model due to hardware constraints, or if you had any other suggestions to work around these limitations.

Your guidance would be greatly appreciated.

Thank you!
Mohammad

**Comment by zhouhanxie** [comment] 2024-12-18 19:32
Hi Mohammad,

It's fine to try a smaller model, but I suspect you'd see some performance degradation. Alternatively, you can try prompting a LLM of your choice to generate the final response, and I think it should preserve factuality of informativeness. Though these are my speculations and are not verified.

Thanks!
Zhouhang

**Comment by MohammadAmanlou** [comment] 2025-01-25 09:11
Hi Zhouhang,

Thanks for your previous response regarding smaller models and LLMs. I’d like to follow up on the dataset details. I noticed that the code references raw (unprocessed) Yelp and Amazon review text in the entailment process, but it’s not included in this repository.

Could you please clarify where I can access or how I can reproduce the original Yelp and Amazon review data you used? For instance, did you use the official Yelp Open Dataset or a special subset from Amazon reviews? Any pointers, links, or guidance would be really helpful for fully replicating your setup.

Thank you in advance!

**Comment by zhouhanxie** [comment] 2025-01-29 21:48
> Hi Zhouhang,
> 
> Thanks for your previous response regarding smaller models and LLMs. I’d like to follow up on the dataset details. I noticed that the code references raw (unprocessed) Yelp and Amazon review text in the entailment process, but it’s not included in this repository.
> 
> Could you please clarify where I can access or how I can reproduce the original Yelp and Amazon review data you used? For instance, did you use the official Yelp Open Dataset or a special subset from Amazon reviews? Any pointers, links, or guidance would be really helpful for fully replicating your setup.
> 
> Thank you in advance!

Hi! The dataset is consistent with prior work (see bottom of readme files on where to find baselines and dataset) - thanks!
